<?php

return [
    /*
    | Județe + sectoare București — folosite la selectoarele de județ.
    */
    'counties' => [
        'Alba',
        'Arad',
        'Argeș',
        'Bacău',
        'Bihor',
        'Bistrița-Năsăud',
        'Botoșani',
        'Brașov',
        'Brăila',
        'Buzău',
        'Caraș-Severin',
        'Călărași',
        'Cluj',
        'Constanța',
        'Covasna',
        'Dâmbovița',
        'Dolj',
        'Galați',
        'Giurgiu',
        'Gorj',
        'Harghita',
        'Hunedoara',
        'Ialomița',
        'Iași',
        'Ilfov',
        'Maramureș',
        'Mehedinți',
        'Mureș',
        'Neamț',
        'Olt',
        'Prahova',
        'Satu Mare',
        'Sălaj',
        'Sibiu',
        'Suceava',
        'Teleorman',
        'Timiș',
        'Tulcea',
        'Vaslui',
        'Vâlcea',
        'Vrancea',
        'București',
        'București - Sector 1',
        'București - Sector 2',
        'București - Sector 3',
        'București - Sector 4',
        'București - Sector 5',
        'București - Sector 6',
    ],
];

